insert into city(name, description, thumbnail, province_id, country_id) values
("Badung", "", "", 1, 1),
("Badung", "", "", 1, 1),
("Bangli", "", "", 1, 1),
("Buleleng", "", "", 1, 1),
("Denpasar", "", "", 1, 1),
("Gianyar", "", "", 1, 1),
("Jembrana", "", "", 1, 1),

("Bangka", "", "", 2, 1),
("Bangka Barat", "", "", 2, 1),
("Bangka Selatan", "", "", 2, 1),
("Bangka Tengah", "", "", 2, 1),
("Belitung", "", "", 2, 1),

("Cilegon", "", "", 3, 1),
("Lebak", "", "", 3, 1),
("Pandeglang", "", "", 3, 1),
("Serang", "", "", 3, 1),
("Tangerang", "", "", 3, 1),

("Bengkulu", "", "", 4, 1),
("Bengkulu Selatan", "", "", 4, 1),
("Bengkulu Tengah", "", "", 4, 1),
("Bengkulu Utara", "", "", 4, 1),
("Kaur", "", "", 4, 1),

("Bantul", "", "", 5, 1),
("Gunung Kidul", "", "", 5, 1),
("Kulon Progo", "", "", 5, 1),
("Sleman", "", "", 5, 1),
("Yogyakarta", "", "", 5, 1),

("Jakarta Barat", "", "", 6, 1),
("Jakarta Pusat", "", "", 6, 1),
("Jakarta Selatan", "", "", 6, 1),
("Jakarta Timur", "", "", 6, 1),
("Jakarta Utara", "", "", 6, 1),
("Kepulauan Seribu", "", "", 6, 1),

("Boalemo", "", "", 7, 1),
("Bone Bolango", "", "", 7, 1),
("Gorontalo", "", "", 7, 1),
("Gorontalo Utara", "", "", 7, 1),
("Pohuwato", "", "", 7, 1),

("Batang Hari", "", "", 8, 1),
("Bungo", "", "", 8, 1),
("Jambi", "", "", 8, 1),
("Kerinci", "", "", 8, 1),
("Merangin", "", "", 8, 1),

("Bandung", "", "", 9, 1),
("Bandung Barat", "", "", 9, 1),
("Banjar", "", "", 9, 1),
("Bogor", "", "", 9, 1),

("Banjarnegara", "", "", 10, 1),
("Banyumas", "", "", 10, 1),
("Batang", "", "", 10, 1),
("Blora", "", "", 10, 1),
("Boyolali", "", "", 10, 1),

("Bangkalan", "", "", 11, 1),
("Banyuwangi", "", "", 11, 1),
("Batu", "", "", 11, 1),
("Blitar", "", "", 11, 1),
("Bojonegoro", "", "", 11, 1),
("Bondowoso", "", "", 11, 1),
("Gresik", "", "", 11, 1),

("Bengkayang", "", "", 12, 1),
("Kapuas Hulu", "", "", 12, 1),
("Kayong Utara", "", "", 12, 1),
("Ketapang", "", "", 12, 1),
("Landak", "", "", 12, 1),

("Banjarbaru", "", "", 13, 1),
("Banjarmasin", "", "", 13, 1),
("Barito Kuala", "", "", 13, 1),
("Hulu Sungai Selatan", "", "", 13, 1),
("Kotabaru", "", "", 13, 1);