-- MySQL Script generated by MySQL Workbench
-- Tue Dec 18 17:09:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema olx
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema olx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `olx` DEFAULT CHARACTER SET utf8 ;
USE `olx` ;

-- -----------------------------------------------------
-- Table `olx`.`Conversation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`Conversation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_seen` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `updated_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `deleted_at` TIMESTAMP NULL,
  `actor_id` INT NOT NULL,
  `last_msg` VARCHAR(45) NULL,
  `is_owner` TINYINT NULL,
  `topic_id` INT NULL COMMENT 'Topic Id == product id / yang lagi di bahas',
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `olx`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NULL,
  `avatar` VARCHAR(45) NULL,
  `cover` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(15) NULL,
  `gender` VARCHAR(15) NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(15) UNIQUE NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `latitude` MEDIUMTEXT NULL,
  `longitude` MEDIUMTEXT NULL,
  `remember_token` VARCHAR(100) NULL,
  `use_whatsapp` TINYINT NULL DEFAULT 0,
  `country_id` INT NULL,
  `province_id` INT NULL,
  `city_id` INT NULL,
  `district_id` INT NULL,
  `village_id` INT NULL,
  `google_token` VARCHAR(255) NULL,
  `facebook_token` VARCHAR(255) NULL,
  `is_news_letter` TINYINT NULL DEFAULT 1,
  `conversation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_Conversation1_idx` (`conversation_id` ASC),
  CONSTRAINT `fk_Users_Conversation1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `olx`.`Conversation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);















-- -----------------------------------------------------
-- Table `olx`.`Province_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`Province_1` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` TEXT(500) NULL,
  `thumbnail` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT current_timestamp,
  `updated_at` TIMESTAMP NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `olx`.`Province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`Province` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT(500) NULL,
  `thumbnail` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `updated_at` TIMESTAMP NULL DEFAULT current_timestamp,
  `Country_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Country_id`),
  INDEX `fk_Province_Country_idx` (`Country_id` ASC),
  CONSTRAINT `fk_Province_Country`
    FOREIGN KEY (`Country_id`)
    REFERENCES `olx`.`Country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `olx`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`City` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(500) NULL,
  `thumbnail` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `updated_at` TIMESTAMP NULL DEFAULT current_timestamp,
  `Province_id` INT UNIQUE NOT NULL,
  `Province_Country_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Province_id`, `Province_Country_id`),
  INDEX `fk_City_Province1_idx` (`Province_id` ASC, `Province_Country_id` ASC),
  CONSTRAINT `fk_City_Province1`
    FOREIGN KEY (`Province_id` , `Province_Country_id`)
    REFERENCES `olx`.`Province` (`id` , `Country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `olx`.`District`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`District` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NOT NULL,
  `description` TEXT(500) NULL,
  `thumbnail` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `updated_at` TIMESTAMP NULL DEFAULT current_timestamp,
  `zip_code` VARCHAR(9) NOT NULL,
  `City_id` INT UNIQUE NOT NULL,
  `City_Province_id` INT UNIQUE NOT NULL,
  `City_Province_Country_id` INT NOT NULL,
  PRIMARY KEY (`id`, `City_id`, `City_Province_id`, `City_Province_Country_id`),
  INDEX `fk_District_City1_idx` (`City_id` ASC, `City_Province_id` ASC, `City_Province_Country_id` ASC),
  CONSTRAINT `fk_District_City1`
    FOREIGN KEY (`City_id` , `City_Province_id` , `City_Province_Country_id`)
    REFERENCES `olx`.`City` (`id` , `Province_id` , `Province_Country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `olx`.`Village`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`Village` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NOT NULL,
  `description` TEXT(500) NULL,
  `thumbnail` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `updated_at` TIMESTAMP NULL DEFAULT current_timestamp,
  `District_id` INT UNIQUE NOT NULL,
  `District_City_id` INT UNIQUE NOT NULL,
  `District_City_Province_id` INT UNIQUE NOT NULL,
  `District_City_Province_Country_id` INT NOT NULL,
  PRIMARY KEY (`id`, `District_id`, `District_City_id`, `District_City_Province_id`, `District_City_Province_Country_id`),
  INDEX `fk_Village_District1_idx` (`District_id` ASC, `District_City_id` ASC, `District_City_Province_id` ASC, `District_City_Province_Country_id` ASC),
  CONSTRAINT `fk_Village_District1`
    FOREIGN KEY (`District_id` , `District_City_id` , `District_City_Province_id` , `District_City_Province_Country_id`)
    REFERENCES `olx`.`District` (`id` , `City_id` , `City_Province_id` , `City_Province_Country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `olx`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`Message` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `text_msg` TEXT(300) NULL,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `reply_id` BIGINT NOT NULL,
  `status_received` TINYINT NULL DEFAULT 0 COMMENT 'status_received = status pengiriman (Pending | Sending | Recive | Read )',
  `conversation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Message_Users1_idx` (`user_id` ASC),
  INDEX `fk_Message_Message1_idx` (`reply_id` ASC),
  INDEX `fk_Message_Conversation1_idx` (`conversation_id` ASC),
  CONSTRAINT `fk_Message_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `olx`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_Message1`
    FOREIGN KEY (`reply_id`)
    REFERENCES `olx`.`Message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_Conversation1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `olx`.`Conversation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olx`.`Message_Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`Message_Image` (
  `id` INT(32) NOT NULL,
  `message_id` BIGINT NOT NULL,
  `name` VARCHAR(32) NULL,
  `slug` VARCHAR(32) NULL,
  `path` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `message_id`),
  INDEX `fk_Message_Image_Message1_idx` (`message_id` ASC),
  CONSTRAINT `fk_Message_Image_Message1`
    FOREIGN KEY (`message_id`)
    REFERENCES `olx`.`Message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olx`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`Product` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `slug_title` VARCHAR(255) NOT NULL,
  `category_id` INT NOT NULL,
  `public_price` INT NOT NULL,
  `is_nego` TINYINT NULL,
  `content_desc`  NOT NULL,
  `country_id` INT NOT NULL,
  `province_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  `district_id` INT NULL,
  `is_condition` TINYINT NULL,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `is_active` TINYINT NULL,
  `is_show` INT NULL COMMENT 'Berapa banyak/sering produk ini di lihat oleh orang ?',
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `olx`.`Users_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`Users_has_Product` (
  `users_id` INT NOT NULL,
  `product_id` INT UNIQUE NOT NULL,
  `is_favorite` TINYINT NULL,
  PRIMARY KEY (`users_id`, `product_id`),
  INDEX `fk_Users_has_Product_Product1_idx` (`product_id` ASC),
  INDEX `fk_Users_has_Product_Users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_Users_has_Product_Users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `olx`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Product_Product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `olx`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `olx`.`Post_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`Post_Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NULL DEFAULT 0,
  `slug` VARCHAR(100) NULL,
  `name` VARCHAR(100) NULL,
  `image` VARCHAR(191) NULL,
  `description` TEXT(300) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Post_Category_Post_Category1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_Post_Category_Post_Category1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `olx`.`Post_Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `olx`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`Posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `date_published` DATETIME NULL,
  `post_title` VARCHAR(80) NOT NULL,
  `post_slug` VARCHAR(100) NOT NULL,
  `post_body` MEDIUMTEXT NOT NULL,
  `post_type` ENUM('blog', 'article') NULL,
  `counter` INT NULL,
  `created_at` TIMESTAMP NULL DEFAULT current_timestamp,
  `update_at` TIMESTAMP NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`),
  INDEX `fk_Posts_Post_Category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_Posts_Post_Category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `olx`.`Post_Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `olx`.`Category_Translation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`Category_Translation` (
  `id` INT NULL,
  `name` VARCHAR(100) NULL,
  `slug` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `language` INT NULL,
  `category_id` INT NULL);


-- -----------------------------------------------------
-- Table `olx`.`Posts_Translation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`Posts_Translation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_title` VARCHAR(45) NULL,
  `post_slug` VARCHAR(100) NULL,
  `post_body`  NULL,
  `language` INT NULL,
  `post_id` INT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `olx`.`Tagline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`Tagline` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `slug` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `language` INT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `olx`.`Posts_has_Tagline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx`.`Posts_has_Tagline` (
  `post_id` INT NOT NULL,
  `tagline_id` INT NOT NULL,
  PRIMARY KEY (`post_id`, `tagline_id`),
  INDEX `fk_Posts_has_Tagline_Tagline1_idx` (`tagline_id` ASC),
  CONSTRAINT `fk_Posts_has_Tagline_Posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `olx`.`Posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posts_has_Tagline_Tagline1`
    FOREIGN KEY (`tagline_id`)
    REFERENCES `olx`.`Tagline` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
